@host = http://127.0.0.1:8000
@react_base_url = {{host}}/api
@public_header = Content-Type: applicatio/json\r\nAccept: application/json\r\nAccept-Language: en
@auth_header = Content-Type: application/json\r\nAccept: application/json\r\nAccept-Language: en\r\nAuthorization: Bearer 12|kCNekUwK1eeYdidpwAkTinay2Jxx7Uax7RwzNp0V41371528
#-------PING------------#
###

//users api's
# @name userRegister
POST {{react_base_url}}/registration HTTP/1.1
{{public_header}}

{ 
    "name":"ravindra",
    "email":"jaylathiya243@gmail.com",
    "password":"shivam@gmail.com",
    "password_confirmation":"shivam@gmail.com"
}
###

# @name userLogin
POST {{react_base_url}}/login HTTP/1.1
{{public_header}}

{
    "email":"shivam@gmail.com",
    "password":"shivam@gmail.com"
}

###

# @name profile
POST {{react_base_url}}/profile HTTP/1.1
{{auth_header}}
###

# @name logout
POST {{react_base_url}}/logout HTTP/1.1
{{auth_header}}
###

# # @name getAllData
# POST {{react_base_url}}/getAll HTTP/1.1
# {{public_header}}
# ###

# @name get
POST {{react_base_url}}/get HTTP/1.1
{{public_header}}

{
    "name":""
}
###

# @name updateprofile
POST {{react_base_url}}/update/1 HTTP/1.1
{{auth_header}}

{
    "name":"raghu",
    "email":"raghv@gmail.com",
    "password":"raghu@123",
    "password_confirmation":"raghu@123"
}

###

# @name productCreate
POST {{react_base_url}}/product/create HTTP/1.1
{{auth_header}}

{
    "product_name":"rav",
    "product_price":50.25
}

### 

# @name productGetAll
POST {{react_base_url}}/product/get HTTP/1.1
{{auth_header}}

{
    "product_name":"ra"
}
###

# @name productDetail
POST {{react_base_url}}/product/detail/5 HTTP/1.1
{{auth_header}}

###

# @name updateProduct
POST {{react_base_url}}/product/update/12 HTTP/1.1
{{auth_header}}

{
    "product_name":"sticker",
    "product_price":25.00
}

###

# @name deleteProduct
POST {{react_base_url}}/product/delete/17 HTTP/1.1
{{auth_header}}

###

# @name makeOrder
POST {{react_base_url}}/order/makeOrder HTTP/1.1
{{auth_header}}

{
    "order_name":"BookOrder",
    "customer_id":23,
    "product_id":6
}
### 

# @name orderGetAll
POST {{react_base_url}}/order/get HTTP/1.1
{{auth_header}}

{
    "order_name":""
}
###

# @name orderDetail
POST {{react_base_url}}/order/detail/4 HTTP/1.1
{{auth_header}}
###

# @name updateOrder
POST {{react_base_url}}/order/update/8 HTTP/1.1
{{auth_header}}

{
    "order_name":"MarkerOrder",
    "customer_id":28,
    "product_id":8
}
### 

# @name deleteOrder
POST {{react_base_url}}/order/delete/6 HTTP/1.1
{{auth_header}}

### 